### ISSUE TITLE
原Repo已暂停更新

### ISSUE THREAD

**Issue by NormanBB** [white-shiro-bai/chinaunicom_freedata#3]
则本项目会继续更新免流所用到的地址吗?

**Comment by white-shiro-bai** [comment]
不会。本项目所用免流地址来自 https://github.com/simo8102/chinaunicom-AutoSignMachine 现在他们换了个私有的方式更新，我跟不上。如果老哥发现了新的免流地址，欢迎提交哈。我现在也缺流量。

**Comment by NormanBB** [comment]
我也是刚接触这种项目。滚动更新是一个吃力不讨好的事情，在考虑着用付费的产品了。

**Comment by white-shiro-bai** [comment]
> 我也是刚接触这种项目。滚动更新是一个吃力不讨好的事情，在考虑着用付费的产品了。

当时也是维护给不舍得买流量，每月只有1G的人，已经没必要了。

**Comment by NormanBB** [comment]
> 不会。本项目所用免流地址来自 https://github.com/simo8102/chinaunicom-AutoSignMachine 现在他们换了个私有的方式更新，我跟不上。如果老哥发现了新的免流地址，欢迎提交哈。我现在也缺流量。

私有的方式就是加QQ群，下载相应软件，在相应网站购买套餐然后开通使用。打不过就加入 :)

分享一篇网上看到的相关文章 [免流研究](https://renyili.org/post/%E5%85%8D%E6%B5%81%E9%97%AE%E9%A2%98%E7%A0%94%E7%A9%B6/)，供后来者参考。
